In [1]:
import numpy as np
from src import sampling

In [2]:
np.random.dirichlet([5,0.4,0.4])

array([9.74211792e-01, 4.61761079e-06, 2.57835907e-02])

In [4]:
from src.utils import fed_avg
import torch
local_weights = [{"a":torch.tensor([1,2,3]), "b":torch.tensor([4,5,6])}, {"a":torch.tensor([5,4,3]), "b":torch.tensor([2,1,0])}]
#expected avg should be 3
dataset_size_per_client = [10000000, 10]
global_weights = fed_avg(local_weights, dataset_size_per_client)
global_weights

{'a': tensor([1.0000, 2.0000, 3.0000]), 'b': tensor([4.0000, 5.0000, 6.0000])}

In [1]:
import os

path = "C:\\Users\\lyada\\Desktop\\Federated-Learning-PyTorch\\save\\objects\\0.2_mnist_vae_3_C[1.0]_iid[2]_E[1]_B[10].pkl"
import pickle

with open(path, 'rb') as f:
    data = pickle.load(f)
print(len(data))
print(len(data[0]))
print(data[0])
print(data[1])
print(data[2])

3
2
[[17118.47621809 16061.88037327 15880.72466823]
 [17893.12191772 17019.89429188 16790.32983398]]
[[1208575.25  1133073.625 1127436.625]
 [2619418.    2324321.75  2299255.   ]]
[[0.02308105 0.02952228 0.03864734]
 [0.32052212 0.50157119 0.52139231]]


In [1]:
from src.utils import get_dataset
class args:
    def __init__(self):
        self.dataset = "mnist"
        self.iid = 1
        self.num_users = 3

a = args()
print(a.dataset)

train_dataset, test_dataset, user_groups = get_dataset(a)

mnist


In [2]:
len(train_dataset)


60000

In [3]:
print(train_dataset[0][0].shape, train_dataset[0][1])

torch.Size([1, 28, 28]) 5


In [4]:
from src.vae.mnist_vae import VaeAutoencoderClassifier
from src.impute import impute_naive
import torch
trained_vae = VaeAutoencoderClassifier(dim_encoding=2)
trained_vae.load_state_dict(torch.load("C:\\Users\\lyada\\Desktop\\Federated-Learning-PyTorch\\vae_data\\models\\global.pth"))
generated_dataset = impute_naive(k=30, trained_vae=trained_vae, initial_dataset=train_dataset)

In [5]:
len(generated_dataset)

60030

In [34]:
import numpy as np
np.argmax(generated_dataset[1][2].detach().numpy())
to_be_zipped = []
for image_ind in range(3):
    to_be_zipped.append((generated_dataset[0][image_ind], np.argmax(generated_dataset[1][image_ind].detach().numpy())))


In [35]:
print(to_be_zipped[0][0].shape, to_be_zipped[0][1])
# to_be_zipped

torch.Size([1, 28, 28]) 3
